version: '3.4'

services:
  sync-react:
    container_name: sync-react
    build:
      context: .
      dockerfile: ./apps/sync-react/Dockerfile
    restart: always
    ports:
      - 3002:3002
    networks:
      - portabl
    volumes:
      - /app/node_modules

  sync-javascript:
    container_name: sync-javascript
    build:
      context: .
      dockerfile: ./apps/sync-javascript/Dockerfile
    restart: always
    tty: true
    ports:
      - 3001:3001
    networks:
      - portabl
    volumes:
      - /app/node_modules

  sync-api:
    container_name: sync-api
    build:
      context: .
      dockerfile: ./apps/sync-api/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - portabl
    volumes:
      - /app/node_modules

  connect-react:
    container_name: connect-react
    build:
      context: .
      dockerfile: ./apps/connect-react/Dockerfile
    restart: always
    ports:
      - 4002:4002
    networks:
      - portabl
    volumes:
      - /app/node_modules

  connect-javascript:
    container_name: connect-javascript
    build:
      context: .
      dockerfile: ./apps/connect-javascript/Dockerfile
    restart: always
    tty: true
    ports:
      - 4001:4001
    networks:
      - portabl
    volumes:
      - /app/node_modules

  connect-api:
    container_name: connect-api
    build:
      context: .
      dockerfile: ./apps/connect-api/Dockerfile
    restart: always
    ports:
      - 4000:4000
    networks:
      - portabl
    volumes:
      - /app/node_modules

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  portabl:
    name: portabl
