version: '3.4'

services:
  portabl-next:
    container_name: portabl-next
    build:
      context: .
      dockerfile: ./apps/portabl-next/Dockerfile
    restart: always
    ports:
      - 4002:3000
    networks:
      - portabl
    volumes:
      - /app/node_modules

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  portabl:
    name: portabl
